import React, { useState } from 'react';
import Head from 'next/head'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { useRouter } from 'next/router'
import { toast } from 'react-toastify';

export default function CreateProduct() {
  const router = useRouter()
  const [title, setTitle]  = useState('create product')

  const saveProduct = (event: any) => {
    event.preventDefault()
    // validate the data
    // sends a post request to the API using axios
    // redirect the user to the products list page
    // display a success flash message
    toast("Product created successfully!")
    router.push('/admin/products')
  }

  return (
    <>
      <Head>
        <title>Create product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{title}</h1>

        <form>
          <input type="name" placeholder="product name" />
          <input type="reference" placeholder="product reference" />

          <button onClick={saveProduct}>Save</button>
        </form>
      </main>
    </>
  )
}