import React, { useState } from 'react';
import Head from 'next/head'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { useRouter } from 'next/router'

export default function ListProducts() {
  const router = useRouter()
  const [title, setTitle]  = useState('List of products, admin only')

  return (
    <>
      <Head>
        <title>List of products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{title}</h1>
        <button onClick={() => router.push('/admin/products/create')}>Create Product</button>
      </main>
    </>
  )
}