import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export default function Login() {

  return (
    <>
      <Head>
        <title>Login page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome back, please login</h1>
        <form>
          <div>
            <input name='email' placeholder='Email' type='email' />
          </div>
          <div>
            <input name='password' placeholder='Password' type='password' />
          </div>
          <button>Connexion</button>
        </form>
      </main>
    </>
  )
}
