import React, { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { useRouter } from 'next/router'
import { toast } from 'react-toastify';
import Button from '@mui/material/Button';

export default function Login() {
  const router = useRouter()
  const [title, setTitle]  = useState('Welcome back, please login!')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  
  const resetForm = (event: any) => {
    event.preventDefault()
    setEmail('')
    setPassword('')
  }

  const handleLogin = (event: any) => {
    event.preventDefault()
    console.log('login the user')
    // TODO data validation (email, password)
    // TODO: sends a post request to the API
    // TODO: save the token on the localstorage
    // TODO: display success flush message
    // TODO: redirect the user to the dashboard
    toast("Welcome Back, Login successfully")
    router.push('/')
  }

  return (
    <>
      <Head>
        <title>Login page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{title}</h1>
        <p>your email is: {email}</p>
        <p>your password is: {password}</p>
        <form>
          <div>
            <input name='email' placeholder='exemple@gmail.com' type='email' value={email} onChange={(event) => setEmail(event.target.value)} />
          </div>
          <div>
            <input name='password' placeholder='Password' type='password' value={password} onChange={(event) => setPassword(event.target.value)} />
          </div>
          <Button variant="outlined" disabled={password.length < 8 || email.length < 2} onClick={handleLogin}>Connexion</Button>
          <button onClick={resetForm}>Reset</button>
        </form>
      </main>
    </>
  )
}